# Generated by Django 6.0.6 on 2026-06-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('Python Development', 'Python Development'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Web Development', 'Web Development'), ('Graphic Designing', 'Graphic Designing'), ('Social Media Marketing', 'Social Media Marketing'), ('Scientific Writing', 'Scientific Writing')], max_length=100)),
                ('registration_type', models.CharField(choices=[('Course Admission', 'Course Admission'), ('Free Demo Class', 'Free Demo Class')], max_length=30)),
                ('payment_method', models.CharField(choices=[('Easypaisa', 'Easypaisa'), ('JazzCash', 'JazzCash'), ('Bank Transfer', 'Bank Transfer')], max_length=30)),
                ('payment_screenshot', models.ImageField(upload_to='payment_screenshots/')),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
