# Generated by Django 6.0.6 on 2026-06-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devexify', '0002_alter_admission_options_alter_admission_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
    ]
