# Generated by Django 6.0.6 on 2026-07-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devexify', '0003_admission_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Course Certificate'),
        ),
    ]
